### ISSUE TITLE
Publish step with plugin occasionally fails

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#172]
**cos-toolkit version:**

**CPU architecture, OS, and Version:**

**Describe the bug**

**To Reproduce**
This seems to occur sporadically in the CI. Never seen this locally

**Expected behavior**

**Logs**
```
⠒  🐋  Pushed image: raccos/releases-opensuse:repository.yaml
fatal error: concurrent map writes

goroutine 413 [running]:
runtime.throw(0x1f7302e, 0x15)
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc0003bf650 sp=0xc0003bf620 pc=0x437172
runtime.mapassign(0x1cb84e0, 0xc0004338f0, 0xc0003bf728, 0x21f5de0)
	/usr/local/go/src/runtime/map.go:676 +0x591 fp=0xc0003bf6d0 sp=0xc0003bf650 pc=0x40ff11
github.com/codegangsta/inject.(*injector).Map(0xc0003a2150, 0x1cdaa00, 0xc000359fb0, 0x14, 0x1f6121a)
	/luetbuild/luet/vendor/github.com/codegangsta/inject/inject.go:142 +0xfe fp=0xc0003bf748 sp=0xc0003bf6d0 pc=0x197917e
github.com/mudler/go-pluggable.(*Bus).propagateEvent.func1(0xc0005739c0)
	/luetbuild/luet/vendor/github.com/mudler/go-pluggable/bus.go:70 +0x15f fp=0xc0003bf820 sp=0xc0003bf748 pc=0x197b5bf
runtime.call16(0xc0006ba0c0, 0xc000541e90, 0xc00000e038, 0x800000008)
	/usr/local/go/src/runtime/asm_amd64.s:550 +0x3e fp=0xc0003bf840 sp=0xc0003bf820 pc=0x46c03e
reflect.Value.call(0x1c22140, 0xc000541e90, 0x13, 0x1f46255, 0x4, 0xc0004f0288, 0x1, 0x1, 0xc0004c1ab8, 0x44efec, ...)
	/usr/local/go/src/reflect/value.go:476 +0x8e7 fp=0xc0003bfa48 sp=0xc0003bf840 pc=0x4e3847
reflect.Value.Call(0x1c22140, 0xc000541e90, 0x13, 0xc0004f0288, 0x1, 0x1, 0x2f987d8, 0xc0004c1b48, 0x479fda)
	/usr/local/go/src/reflect/value.go:337 +0xb9 fp=0xc0003bfac8 sp=0xc0003bfa48 pc=0x4e2d19
github.com/codegangsta/inject.(*injector).Invoke(0xc0003a2150, 0x1c22140, 0xc000541e90, 0xc0004c1be8, 0x4791b4, 0xc0006ba030, 0xc00053ab00, 0x0)
	/luetbuild/luet/vendor/github.com/codegangsta/inject/inject.go:102 +0x31c fp=0xc0003bfb88 sp=0xc0003bfac8 pc=0x1978b3c
github.com/mudler/go-pluggable.(*Bus).Listen.func1()
	/luetbuild/luet/vendor/github.com/mudler/go-pluggable/bus.go:44 +0x44 fp=0xc0003bfbd8 sp=0xc0003bfb88 pc=0x197b3e4
runtime.call16(0xc0006ba000, 0xc0005726e0, 0x2f987d8, 0x0)
	/usr/local/go/src/runtime/asm_amd64.s:550 +0x3e fp=0xc0003bfbf8 sp=0xc0003bfbd8 pc=0x46c03e
reflect.Value.call(0x1bff4c0, 0xc0005726e0, 0x13, 0x1f46255, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:476 +0x8e7 fp=0xc0003bfe00 sp=0xc0003bfbf8 pc=0x4e3847
reflect.Value.Call(0x1bff4c0, 0xc0005726e0, 0x13, 0x0, 0x0, 0x0, 0xc0005197b0, 0x10, 0x4bc065)
	/usr/local/go/src/reflect/value.go:337 +0xb9 fp=0xc0003bfe80 sp=0xc0003bfe00 pc=0x4e2d19
github.com/chuckpreslar/emission.(*Emitter).Emit.func1(0xc0004e0850, 0xc000482990, 0x1c37580, 0xc00041d7c0, 0x0, 0x0, 0x0, 0x1bff4c0, 0xc0005726e0, 0x13)
	/luetbuild/luet/vendor/github.com/chuckpreslar/emission/emitter.go:209 +0x4ac fp=0xc0003bff90 sp=0xc0003bfe80 pc=0x197834c
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0003bff98 sp=0xc0003bff90 pc=0x46d961
created by github.com/chuckpreslar/emission.(*Emitter).Emit
	/luetbuild/luet/vendor/github.com/chuckpreslar/emission/emitter.go:184 +0x1c5

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0004e0858)
	/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc0004e0850)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65
github.com/chuckpreslar/emission.(*Emitter).Emit(0xc000482990, 0x1c37580, 0xc00041d7c0, 0x0, 0x0, 0x0, 0x45328f)
	/luetbuild/luet/vendor/github.com/chuckpreslar/emission/emitter.go:213 +0x1ec
github.com/mudler/go-pluggable.(*Bus).Publish(0xc000482980, 0xc0005739c0, 0x0)
	/luetbuild/luet/vendor/github.com/mudler/go-pluggable/bus.go:54 +0xdd
github.com/mudler/go-pluggable.(*Manager).Publish(0xc0004829c0, 0x1f6121a, 0xf, 0x1e1e080, 0xc000424af0, 0x2, 0x0, 0x0)
	/luetbuild/luet/vendor/github.com/mudler/go-pluggable/manager.go:53 +0x146
github.com/mudler/luet/pkg/compiler/backend.(*SimpleDocker).Push(0x2f987d8, 0xc000d9a600, 0x28, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/luetbuild/luet/pkg/compiler/backend/simpledocker.go:157 +0x36c
github.com/mudler/luet/pkg/installer.pushImage(0x2255750, 0x2f987d8, 0xc000d9a600, 0x28, 0x2f98701, 0x0, 0xc000d9a600)
	/luetbuild/luet/pkg/installer/repository_docker.go:124 +0x11a
github.com/mudler/luet/pkg/installer.(*dockerRepositoryGenerator).pushFileFromArtifact(0xc0004ef5c0, 0xc0006dc698, 0xc000d9a600, 0x28, 0x2, 0xc000d9a600)
	/luetbuild/luet/pkg/installer/repository_docker.go:133 +0x239
github.com/mudler/luet/pkg/installer.(*dockerRepositoryGenerator).pushRepoMetadata(0xc0004ef5c0, 0xc0007a87b0, 0x2b, 0xc0006f6ee0, 0x0, 0x0)
	/luetbuild/luet/pkg/installer/repository_docker.go:156 +0x2ae
github.com/mudler/luet/pkg/installer.(*dockerRepositoryGenerator).Generate(0xc0004ef5c0, 0xc0006f6ee0, 0x7ffcc1ca4f85, 0x18, 0x0, 0x0, 0x0)
	/luetbuild/luet/pkg/installer/repository_docker.go:258 +0x8c5
github.com/mudler/luet/pkg/installer.(*LuetSystemRepository).Write(0xc0006f6ee0, 0x7ffcc1ca4f85, 0x18, 0x100, 0xc00000a290, 0x6)
	/luetbuild/luet/pkg/installer/repository.go:635 +0x90
github.com/mudler/luet/cmd.glob..func7(0x2f3b640, 0xc0000c2d80, 0x0, 0x17)
	/luetbuild/luet/cmd/create-repo.go:157 +0xdb8
github.com/spf13/cobra.(*Command).execute(0x2f3b640, 0xc0000c2c00, 0x17, 0x18, 0x2f3b640, 0xc0000c2c00)
	/luetbuild/luet/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2f39ea0, 0xb, 0x0, 0x0)
	/luetbuild/luet/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/luetbuild/luet/vendor/github.com/spf13/cobra/command.go:895
github.com/mudler/luet/cmd.Execute()
	/luetbuild/luet/cmd/root.go:175 +0xd5
main.main()
	/luetbuild/luet/main.go:10 +0x25

goroutine 9 [chan receive]:
github.com/moby/buildkit/util/pull.newResolverCache.func1(0xc0003881c0, 0xc00048a2d0)
	/luetbuild/luet/vendor/github.com/moby/buildkit/util/pull/resolver.go:174 +0x49
created by github.com/moby/buildkit/util/pull.newResolverCache
	/luetbuild/luet/vendor/github.com/moby/buildkit/util/pull/resolver.go:172 +0x9a

goroutine 10 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x2f5de00)
	/luetbuild/luet/vendor/k8s.io/klog/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
	/luetbuild/luet/vendor/k8s.io/klog/klog.go:411 +0xd8

goroutine 417 [select]:
net/http.(*persistConn).writeLoop(0xc0007ad320)
	/usr/local/go/src/net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1744 +0xc9c

goroutine 411 [sleep]:
time.Sleep(0x5f5e100)
	/usr/local/go/src/runtime/time.go:193 +0xd2
github.com/briandowns/spinner.(*Spinner).Start.func1(0xc000412d10)
	/luetbuild/luet/vendor/github.com/briandowns/spinner/spinner.go:319 +0x53
created by github.com/briandowns/spinner.(*Spinner).Start
	/luetbuild/luet/vendor/github.com/briandowns/spinner/spinner.go:281 +0x87

goroutine 420 [select]:
net/http.(*persistConn).writeLoop(0xc0007ad560)
	/usr/local/go/src/net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1744 +0xc9c

goroutine 384 [IO wait]:
internal/poll.runtime_pollWait(0x7efd99e89b30, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000325818, 0x72, 0x1700, 0x17b0, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000325800, 0xc00042f000, 0x17b0, 0x17b0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000325800, 0xc00042f000, 0x17b0, 0x17b0, 0x17a3, 0xc0002d2fa0, 0xd)
	/usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc00000e4f8, 0xc00042f000, 0x17b0, 0x17b0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:183 +0x91
crypto/tls.(*atLeastReader).Read(0xc0004f01c8, 0xc00042f000, 0x17b0, 0x17b0, 0xc0004bf9f8, 0x2f5e860, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:776 +0x63
bytes.(*Buffer).ReadFrom(0xc0002d3078, 0x21f5d20, 0xc0004f01c8, 0x40b7e5, 0x1ced600, 0x1ec0160)
	/usr/local/go/src/bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc0002d2e00, 0x21f8600, 0xc00000e4f8, 0x5, 0xc00000e4f8, 0x40da5b)
	/usr/local/go/src/crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc0002d2e00, 0x0, 0x0, 0xc0004bfe88)
	/usr/local/go/src/crypto/tls/conn.go:605 +0x115
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0xc0002d2e00, 0xc000710000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1276 +0x165
net/http.(*persistConn).Read(0xc0007ad320, 0xc000710000, 0x1000, 0x1000, 0xc0004bfdc4, 0x2, 0x2)
	/usr/local/go/src/net/http/transport.go:1922 +0x77
bufio.(*Reader).fill(0xc000965bc0)
	/usr/local/go/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).Peek(0xc000965bc0, 0x1, 0x0, 0x1, 0x1, 0x1, 0x0)
	/usr/local/go/src/bufio/bufio.go:139 +0x4f
net/http.(*persistConn).readLoop(0xc0007ad320)
	/usr/local/go/src/net/http/transport.go:2083 +0x1a8
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1743 +0xc77

goroutine 419 [IO wait]:
internal/poll.runtime_pollWait(0x7efd99e893f0, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000325f18, 0x72, 0x1700, 0x17b0, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000325f00, 0xc000430800, 0x17b0, 0x17b0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000325f00, 0xc000430800, 0x17b0, 0x17b0, 0x17a3, 0xc0002d36a0, 0xd)
	/usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc00000e588, 0xc000430800, 0x17b0, 0x17b0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:183 +0x91
crypto/tls.(*atLeastReader).Read(0xc0003de360, 0xc000430800, 0x17b0, 0x17b0, 0x8, 0xc0003b4000, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:776 +0x63
bytes.(*Buffer).ReadFrom(0xc0002d3778, 0x21f5d20, 0xc0003de360, 0x40b7e5, 0x1ced600, 0x1ec0160)
	/usr/local/go/src/bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc0002d3500, 0x21f8600, 0xc00000e588, 0x5, 0xc00000e588, 0x203000)
	/usr/local/go/src/crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc0002d3500, 0x0, 0x0, 0x439e9c)
	/usr/local/go/src/crypto/tls/conn.go:605 +0x115
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0xc0002d3500, 0xc000730000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1276 +0x165
net/http.(*persistConn).Read(0xc0007ad560, 0xc000730000, 0x1000, 0x1000, 0xc0001a2a80, 0xc0004bad40, 0x405775)
	/usr/local/go/src/net/http/transport.go:1922 +0x77
bufio.(*Reader).fill(0xc002126c60)
	/usr/local/go/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).Peek(0xc002126c60, 0x1, 0x0, 0x1, 0x4, 0x1, 0x3)
	/usr/local/go/src/bufio/bufio.go:139 +0x4f
net/http.(*persistConn).readLoop(0xc0007ad560)
	/usr/local/go/src/net/http/transport.go:2083 +0x1a8
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1743 +0xc77
```

**Additional context**
https://github.com/rancher-sandbox/cOS-toolkit/runs/2534101268

**Comment by mudler** [comment]
I think I've tracked it back to the injector not being completely thread safe. https://github.com/mudler/go-pluggable/commit/630c4c90b1c377754c45c1e85bbd1116133b91c8 refactors the code and should get rid of the racing part. It still needs a new luet version with the library bumped.
