### ISSUE TITLE
yip fails to parse boot commands

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#564]
**To Reproduce**
See logs

**Expected behavior**
To not panic

**Logs**
```
$ cat > /tmp/cmdline <<EOF
ip=dhcp rd.cos.disable rd.break=pre-mount rd.live.debug=1 rd.noverifyssl root=live:http://10.84.132.1:79/harvester/master/harvester-rootfs-amd64.squashfs console=tty1 harvester.install.automatic=true harvester.install.config_url=http://10.84.132.1:79/harvester/master/config-create.yaml boot_cmd="echo include_ping_test=yes >> /etc/conf.d/net-online" boot_cmd="echo ping_test_host=10.84.132.1  >> /etc/conf.d/net-online" boot_cmd="ip a > /tmp/nic_status.txt"
EOF

$ yip -d -s rootfs /tmp/cmdline
INFO[0000] yip version 0.9.8-g814c5ba0839f1a60e2ca8e829f8acc2e7f1566c7 2021-08-30 12:13:55 UTC
panic: interface conversion: interface {} is bool, not map[string]interface {}

goroutine 1 [running]:
github.com/mudler/yip/pkg/schema.jq(0xc000501570, 0x9, 0xc0004dd950, 0x2, 0x2, 0xc000501570)
	/luetbuild/go/src/github.com/mudler/yip/pkg/schema/schema.go:240 +0x265
github.com/mudler/yip/pkg/schema.dotToYAML(0xc0004dd260, 0x1cc, 0xc0004dd260, 0xc00054c000, 0x1cc, 0x0)
	/luetbuild/go/src/github.com/mudler/yip/pkg/schema/schema.go:248 +0x1e5
github.com/mudler/yip/pkg/schema.DotNotationModifier(0xc0003a9a00, 0x1cc, 0x200, 0xc0003a9a00, 0x1cc, 0x200, 0x0, 0x0)
	/luetbuild/go/src/github.com/mudler/yip/pkg/schema/schema.go:215 +0x6b
github.com/mudler/yip/pkg/schema.FromFile(0x7ffec9df4b0c, 0xc, 0x18fa228, 0x2210740, 0x178ea10, 0x7ffec9df4b0c, 0xc, 0xc000547b08, 0x0, 0x0)
	/luetbuild/go/src/github.com/mudler/yip/pkg/schema/schema.go:191 +0xb6
github.com/mudler/yip/pkg/schema.Load(0x7ffec9df4b0c, 0xc, 0x18fa228, 0x2210740, 0x178ea18, 0x178ea10, 0x0, 0xc00041fbb0, 0x5adc46)
	/luetbuild/go/src/github.com/mudler/yip/pkg/schema/schema.go:163 +0x86
github.com/mudler/yip/pkg/executor.(*DefaultExecutor).run(0xc0004cc7c0, 0x7ffec9df4b07, 0x4, 0x7ffec9df4b0c, 0xc, 0x18fa228, 0x2210740, 0x18dee80, 0x2210a78, 0x178ea18, ...)
	/luetbuild/go/src/github.com/mudler/yip/pkg/executor/default.go:86 +0x73
github.com/mudler/yip/pkg/executor.(*DefaultExecutor).runStage(0xc0004cc7c0, 0x7ffec9df4b07, 0x4, 0x7ffec9df4b0c, 0xc, 0x18fa228, 0x2210740, 0x18dee80, 0x2210a78, 0xc000142040, ...)
	/luetbuild/go/src/github.com/mudler/yip/pkg/executor/default.go:106 +0x2a5
github.com/mudler/yip/pkg/executor.(*DefaultExecutor).Run(0xc0004cc7c0, 0x7ffec9df4b07, 0x4, 0x18fa228, 0x2210740, 0x18dee80, 0x2210a78, 0xc0004cc780, 0x1, 0x4, ...)
	/luetbuild/go/src/github.com/mudler/yip/pkg/executor/default.go:122 +0xef
github.com/mudler/yip/cmd.glob..func1(0x21c2e40, 0xc0004cc780, 0x1, 0x4)
	/luetbuild/go/src/github.com/mudler/yip/cmd/root.go:107 +0x2b5
github.com/spf13/cobra.(*Command).execute(0x21c2e40, 0xc00013e010, 0x4, 0x4, 0x21c2e40, 0xc00013e010)
	/luetbuild/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x21c2e40, 0x41aa01, 0x0, 0x0)
	/luetbuild/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/luetbuild/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/mudler/yip/cmd.Execute()
	/luetbuild/go/src/github.com/mudler/yip/cmd/root.go:114 +0x2d
main.main()
	/luetbuild/go/src/github.com/mudler/yip/main.go:21 +0x25
``

**Comment by Itxaka** [comment]
This seems to be due to how we split the ingested file:

https://github.com/mudler/yip/blob/master/pkg/schema/schema.go#L266

This means that we read from the file and split based on whitespace, but on *any* whitespace, which means that things like commands will also get split, resulting in a Frankenstein of output that turns into errors, i.e.:

`boot_cmd="echo ping_test_host=10.84.132.1  >> /etc/conf.d/net-online"` gets splitted into:

```
[boot_cmd="echo]
[ping_test_host=10.84.132.1]
[>>]
[/etc/conf.d/net-online"]
```

**Comment by mudler** [comment]
> This seems to be due to how we split the ingested file:
> 
> https://github.com/mudler/yip/blob/master/pkg/schema/schema.go#L266
> 
> This means that we read from the file and split based on whitespace, but on _any_ whitespace, which means that things like commands will also get split, resulting in a Frankenstein of output that turns into errors, i.e.:
> 
> `boot_cmd="echo ping_test_host=10.84.132.1 >> /etc/conf.d/net-online"` gets splitted into:
> 
> ```
> [boot_cmd="echo]
> [ping_test_host=10.84.132.1]
> [>>]
> [/etc/conf.d/net-online"]
> ```

I think we should start by not panic'ing, then we can later iterate on how to support spaces in the commands

**Comment by Itxaka** [comment]
PR at https://github.com/mudler/yip/pull/22
